; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	c:\cs\cpp\sinapprox\sinapprox\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UxhUxkkUhrmzkkilcUhrmzkkilcUivovzhvUhgwzucOlyq@B5423E2469C616A7
;	COMDAT ___@@_PchSym_@00@UxhUxkkUhrmzkkilcUhrmzkkilcUivovzhvUhgwzucOlyq@B5423E2469C616A7
_BSS	SEGMENT
___@@_PchSym_@00@UxhUxkkUhrmzkkilcUhrmzkkilcUivovzhvUhgwzucOlyq@B5423E2469C616A7 DD 01H DUP (?)
_BSS	ENDS
END
