; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	C:\CS\Cpp\SinApprox\SinApprox\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UxhUxkkUhrmzkkilcUhrmzkkilcUwvyftUhgwzucOlyq@B5423E2469C616A7
;	COMDAT ___@@_PchSym_@00@UxhUxkkUhrmzkkilcUhrmzkkilcUwvyftUhgwzucOlyq@B5423E2469C616A7
_BSS	SEGMENT
___@@_PchSym_@00@UxhUxkkUhrmzkkilcUhrmzkkilcUwvyftUhgwzucOlyq@B5423E2469C616A7 DD 01H DUP (?)
_BSS	ENDS
END
